# Number of times each experiment is repeated
nreps: 5

# Random seed used for reproducibility
rseed: 0

# Metrics computed
metrics: [NESS, JSD, time]

display:
    value: false             # Display 1D and 2D density plots on the screen
    display_path: results/   # If value is true, save the plots as a .png in the provided path

    animation: {value: true,                    # Compile the sequence of visualized sampling steps into an animation
                fps: 1,                         # Frames per second used for the animation
                animation_path: results/anim/}  # If value is true, save the plots as a .png in the provided path

output:
    make_plots: true
    plots_path: results/
    plots_dpi: 1200