# Define the target densities used for evaluation and label their categories and provide evaluation parameters
targets:
    - name: uniform
      type: distributions.benchden.BenchDenUniform
      params: {}
      space_size: 2.0
      batch_size: 2
      nsamples: 100
      nsamples_eval: 200
      domain_min: np.array([-.1])
      domain_max: np.array([1.1])
      tags: [benchden, low_kurtosis, low_skew]

    - name: exponential
      type: distributions.benchden.BenchDenExponential
      params: {}
      space_size: 6.0
      batch_size: 2
      nsamples: 100
      nsamples_eval: 200
      domain_min: np.array([-.1])
      domain_max: np.array([6.0])
      tags: [benchden, low_kurtosis, low_skew]

    - name: maxwell
      type: distributions.benchden.BenchDenMaxwell
      params: {}
      space_size: 6.0
      batch_size: 2
      nsamples: 100
      nsamples_eval: 200
      domain_min: np.array([-.1])
      domain_max: np.array([6.0])
      tags: [benchden, low_kurtosis, low_skew]

    - name: laplace
      type: distributions.benchden.BenchDenLaplace
      params: {}
      space_size: 10.0
      batch_size: 2
      nsamples: 100
      nsamples_eval: 200
      domain_min: np.array([-10.0])
      domain_max: np.array([10.0])
      tags: [benchden, low_kurtosis, low_skew]
