# Define the target densities used for evaluation and label their categories and provide evaluation parameters
targets:
    - name: banana2D
      type: distributions.rare.banana2d.Banana2D
      params: {dims: 2}
      batch_size: 32
      nsamples: 12000
      nsamples_eval: 2000
      domain_min: np.array([-15, -15])
      domain_max: np.array([15, 15])
      tags: [benchden, low_kurtosis, low_skew]
