# This is a benchmark of 5-modal GMMs from 1 to 7 dimensions with mu = U(-5, 5), sigma= diag( U(0.01, .5) )
targets:
    - name: normal
      type: distributions.CGaussianMixtureModel
      params: { means: [[ 0.54992115, 3.08838697, 2.38963784,-0.79612206,-3.907443  ]],
                sigmas: [[0.15814429,0.18852918,0.28064028,0.26614025,0.26223548]],
                weights: [1.],
                support: [[-1., 1.,-1.,-4.,-7.], [ 2., 5., 6., 4., 0.]]}
      batch_size: 2048
      nsamples: 1000000
      nsamples_eval: 5000
